2021_2022Frame/2021_2022Frame/Controllers/BaoDuongController.cs
using _2021_2022Frame.Models;
using Microsoft.AspNetCore.Mvc;

namespace _2021_2022Frame.Controllers
{
    public class BaoDuongController : Controller
    {
        public IActionResult chonsoxe()
        {
            return View();
        }

        public IActionResult lietkesuachua(string soxe)
        {
            StoreContext context = new StoreContext("server=127.0.0.1;user id=root;password=;port=3306;database=quanlygara;");
            ViewBag.listBD = context.getbaoduong(soxe);
            return View();
        }

        public IActionResult chitietbaoduong(string Mabd)
        {
            StoreContext context = new StoreContext("server=127.0.0.1;user id=root;password=;port=3306;database=quanlygara;");
            ViewBag.CTBD = context.chitietbaoduong(Mabd);
            ViewBag.listCV = context.getcongviec(Mabd);
            return View();
        }
        public IActionResult suabaoduong(string Mabd)
        {
            StoreContext context = new StoreContext("server=127.0.0.1;user id=root;password=;port=3306;database=quanlygara;");
            ViewBag.baoduong = context.suabaoduong(Mabd);
            return View();
        }
        public IActionResult capnhatbd(baoduong baoduong)
        {
            StoreContext context = new StoreContext("server=127.0.0.1;user id=root;password=;port=3306;database=quanlygara;");
            context.capnhatbd(baoduong);
            return View("lietkesuachua");
        }
    }
}

2021_2022Frame/2021_2022Frame/Controllers/CongViecController.cs
using _2021_2022Frame.Models;
using Microsoft.AspNetCore.Mvc;

namespace _2021_2022Frame.Controllers
{
    public class CongViecController : Controller
    {
        public IActionResult themcongviec()
        {
            return View();
        }
        public IActionResult themcv(congviec cv)
        {
            StoreContext context = new StoreContext("server=127.0.0.1;user id=root;password=;port=3306;database=quanlygara;");
            context.themcongviec(cv);
            return View("themcongviec");
        }
        public IActionResult xoacv(string Mabd, string Macv)
        {
            StoreContext context = new StoreContext("server=127.0.0.1;user id=root;password=;port=3306;database=quanlygara;");
            context.xoacongviec(Mabd, Macv);
            return View("/CongViec/chitietbaoduong");
        }
    }
}

2021_2022Frame/2021_2022Frame/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _2021_2022Frame</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_2021_2022Frame.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_2021_2022Frame</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CongViec" asp-action="themcongviec">Câu 1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="BaoDuong" asp-action="chonsoxe">Câu 2</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - _2021_2022Frame - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>