2019-2020cuoiky/2019-2020cuoiky/Controllers/CN_TCController.cs
using _2019_2020cuoiky.Models;
using Microsoft.AspNetCore.Mvc;

namespace _2019_2020cuoiky.Controllers
{
    public class CN_TCController : Controller
    {
        public IActionResult NhapSoTC()
        {
            return View();
        }

        public IActionResult LietKeTC(int SoTrieuChung)
        {
            //StoreContext context = HttpContext.RequestServices.GetService(typeof(_2019_2020cuoiky.Models.StoreContext)) as StoreContext;
            StoreContext context = new StoreContext("server=127.0.0.1;user id=root;password=;port=3306;database=cachlycovid19;");
            ViewBag.listCNTC = context.LietKeTC(SoTrieuChung);
            return View();
        }
    }
}

2019-2020cuoiky/2019-2020cuoiky/Controllers/DiemCachLyController.cs
using _2019_2020cuoiky.Models;
using Microsoft.AspNetCore.Mvc;

namespace _2019_2020cuoiky.Controllers
{
    public class DiemCachLyController : Controller
    {
        public IActionResult NhapDCL()
        {
            return View();
        }

        public IActionResult ThemDCL(DiemCachLy dcl)
        {
            //StoreContext context = HttpContext.RequestServices.GetService(typeof(_2019_2020cuoiky.Models.StoreContext)) as StoreContext;
            StoreContext context = new StoreContext("server=127.0.0.1;user id=root;password=;port=3306;database=cachlycovid19;");
            context.ThemDCL(dcl);
            return View("NhapDCL");
        }

        public IActionResult LietKeDCL()
        {
            //StoreContext context = HttpContext.RequestServices.GetService(typeof(_2019_2020cuoiky.Models.StoreContext)) as StoreContext;
            StoreContext context = new StoreContext("server=127.0.0.1;user id=root;password=;port=3306;database=cachlycovid19;");
            ViewBag.listDCL = context.getAllDCL();
            return View();
        }
    }
}

2019-2020cuoiky/2019-2020cuoiky/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _2019_2020cuoiky</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_2019_2020cuoiky.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_2019_2020cuoiky</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DiemCachLy" asp-action="NhapDCL">Câu 1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CN_TC" asp-action="NhapSoTC">Câu 2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DiemCachLy" asp-action="LietKeDCL">Câu 3</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - _2019_2020cuoiky - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>