BaoTriCanHoChungCu_HK1_20_21/BaoTriCanHoChungCu_HK1_20_21/BaoTriCanHoChungCu_HK1_20_21/Controllers/CanHoController.cs
using Microsoft.AspNetCore.Mvc;
using BaoTriCanHoChungCu_HK1_20_21.Models;
namespace BaoTriCanHoChungCu_HK1_20_21.Controllers
{
    public class CanHoController : Controller
    {
        public IActionResult NhapCanHo()
        {
            return View();
        }

        public IActionResult ThemCanHo(CanHo ch)
        {
            StoreContext context = HttpContext.RequestServices.GetService(typeof(BaoTriCanHoChungCu_HK1_20_21.Models.StoreContext)) as StoreContext;
            context.ThemCanHo(ch);
            return View("NhapCanHo");
        }
    }
}

BaoTriCanHoChungCu_HK1_20_21/BaoTriCanHoChungCu_HK1_20_21/BaoTriCanHoChungCu_HK1_20_21/Controllers/NhanVienController.cs
using BaoTriCanHoChungCu_HK1_20_21.Models;
using Microsoft.AspNetCore.Mvc;

namespace BaoTriCanHoChungCu_HK1_20_21.Controllers
{
    public class NhanVienController : Controller
    {
        public IActionResult LietKeNhanVienCoNLanSua()
        {
            return View();
        }

        public IActionResult CacNhanVienCoNLanSua(int num)
        {
            StoreContext context = HttpContext.RequestServices.GetService(typeof(BaoTriCanHoChungCu_HK1_20_21.Models.StoreContext)) as StoreContext;
            return View(context.CacNhanVienCoNLanSua(num));
        }

        public IActionResult LietKeNhanVien()
        {
            StoreContext context = HttpContext.RequestServices.GetService(typeof(BaoTriCanHoChungCu_HK1_20_21.Models.StoreContext)) as StoreContext;
            return View(context.LietKeNhanVien());
        }
    }
}

BaoTriCanHoChungCu_HK1_20_21/BaoTriCanHoChungCu_HK1_20_21/BaoTriCanHoChungCu_HK1_20_21/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BaoTriCanHoChungCu_HK1_20_21</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BaoTriCanHoChungCu_HK1_20_21.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BaoTriCanHoChungCu_HK1_20_21</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>*@
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CanHo" asp-action="NhapCanHo">Cau 1</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NhanVien" asp-action="LietKeNhanVienCoNLanSua">Cau2</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NhanVien" asp-action="LietKeNhanVien">Cau3</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BaoTriCanHoChungCu_HK1_20_21 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>